(package "lsp-metals"
         "1.0.0"
         "Scala Client settings ")

(package-file "lsp-metals.el")

(files "*.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "scala-mode")
(depends-on "lsp-mode")
(depends-on "lsp-treemacs")
(depends-on "dap-mode")
(depends-on "dash")
(depends-on "f")
(depends-on "ht")
(depends-on "treemacs")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
